#!/bin/bash

./app.py &

sleep 1.5

rm -Rf output
mkdir output

cp -r static output/static
cd output
wget -q http://127.0.0.1:5000/index.html
wget -q http://127.0.0.1:5000/code.html
wget -q http://127.0.0.1:5000/articles.html
wget -q http://127.0.0.1:5000/team.html
wget -q http://127.0.0.1:5000/whitepaper.html
wget -q http://127.0.0.1:5000/apply.html

kill %1

cd ..

rsync -r output/ nicksweeting.com:/var/www/80/oddslingers

echo "[√] Build & Deploy to labs.oddslingers.com complete."
