#!/usr/bin/env python3

import os
from jinja2 import Environment, FileSystemLoader, select_autoescape

TEMPLATE_DIR = 'templates'
OUTPUT_DIR = 'html'

GLOBAL_CONTEXT = {
    'title': 'OddSlingers Labs',
    'year': 2018,
}


env = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    autoescape=select_autoescape(['html', 'xml']),
)

pages = [fname for fname in os.listdir(TEMPLATE_DIR) if fname.endswith('.html')]
for template in pages:
    page = env.get_template(os.path.join(TEMPLATE_DIR, template))

    with open(os.path.join(OUTPUT_DIR, template), 'w+') as f:
        f.write(page.render(**GLOBAL_CONTEXT))

print(f'[√] Done building. View output: {OUTPUT_DIR}/index.html')
