#!/bin/bash

normal=$(tput sgr0)
red=${txtbld}$(tput setaf 1)
blue=${txtbld}$(tput setaf 4)
green=${txtbld}$(tput setaf 2)
white=${txtbld}$(tput setaf 7)
current_branch=$(git rev-parse --abbrev-ref HEAD)

echo "$blue[+] Starting Flask server...$normal"
./server > /dev/null &
sleep 1.5

# Recreate output folder
rm -Rf output
mkdir -p output/posts
cp -r static output/static
./server --pages > output/pages.txt
./server --posts > output/posts.txt

echo "$blue[+] Building pages HTML...$normal"
(cd output; wget -q $(<pages.txt))
(cd output/posts; wget -q $(<../posts.txt))

# echo "$red[*] Stopping Flask server...$normal"
kill %1 > /dev/null
echo ""
echo "$green[√] Build of static site complete.$normal"
echo ""
echo ""
echo "$red Deploying & committing in 3 sec, press Ctrl+C to cancel..."
echo ""
sleep 3
echo ""
echo "$blue[^] Pushing build to git...$normal"
git add output
git commit -q --short -m "built static site" > /dev/null
git push origin "$current_branch":live --force

echo "$blue[^] Deploying to https://labs.oddslingers.com...$normal"
rsync -r output/ labs.oddslingers.com:/opt/labs.oddslingers.com/output
# ssh labs.oddslingers.com "cd /opt/labs.oddslingers.com; git checkout -f live; git pull"

echo "$green[√] Deploy to https://labs.oddslingers.com complete.$normal"
